# Generated by Django 5.2 on 2026-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daaluser',
            name='is_transporter',
            field=models.BooleanField(default=False),
        ),
    ]
