# Generated by Django 5.2 on 2026-01-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0002_daaluser_is_transporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daaluser',
            old_name='is_broker',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='daaluser',
            old_name='is_customer',
            new_name='is_seller',
        ),
    ]
