# Generated by Django 5.2 on 2026-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0003_rename_is_broker_daaluser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daaluser',
            name='plain_text_password_temp',
            field=models.CharField(blank=True, help_text='⚠️ SECURITY RISK: Plain text password storage - DO NOT USE IN PRODUCTION', max_length=128, null=True),
        ),
    ]
