# Generated by Django 5.2 on 2026-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0004_daaluser_plain_text_password_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daaluser',
            name='plain_text_password_temp',
        ),
        migrations.AddField(
            model_name='daaluser',
            name='char_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
