# Generated by Django 5.2 on 2026-01-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0005_remove_daaluser_plain_text_password_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daaluser',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST (Goods and Services Tax) Number - 15 characters', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='is_both_sellerandbuyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN (Permanent Account Number) - 10 characters', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('transporter', 'Transporter'), ('both_sellerandbuyer', 'Both Seller and Buyer')], default='buyer', max_length=20),
        ),
    ]
