# Generated by Django 5.2 on 2026-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0007_categorymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daaluser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
