# Generated by Django 5.2 on 2026-01-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0008_alter_daaluser_gst_number_alter_daaluser_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymaster',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='categorymaster',
            name='type',
        ),
        migrations.CreateModel(
            name='subCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers_app.categorymaster')),
            ],
            options={
                'verbose_name': 'Sub-Category Master',
                'verbose_name_plural': 'Sub-Category Masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
