# Generated by Django 5.2 on 2026-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0009_remove_categorymaster_subtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polish_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polish Master',
                'verbose_name_plural': 'Polish Masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
