# Generated by Django 5.2 on 2026-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0011_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daaluser',
            name='mobile',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
