# Generated by Django 5.2 on 2026-02-02 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0012_alter_daaluser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('transporter', 'Transporter'), ('both_sellerandbuyer', 'Both Seller and Buyer')], max_length=20)),
                ('module', models.CharField(choices=[('user_management', 'User Management'), ('category_management', 'Category Management'), ('subcategory_management', 'Subcategory Management'), ('polish_management', 'Polish Management'), ('product_management', 'Product Management'), ('product_image_management', 'Product Image Management')], max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'module', 'action'],
                'unique_together': {('role', 'module', 'action')},
            },
        ),
    ]
