# Generated by Django 6.0.2 on 2026-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0013_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='daaluser',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth in YYYY-MM-DD format', null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='gst_image',
            field=models.ImageField(blank=True, help_text='Upload GST certificate image', null=True, upload_to='gst_images/'),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='pan_image',
            field=models.ImageField(blank=True, help_text='Upload PAN card image', null=True, upload_to='pan_images/'),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
