# Generated by Django 6.0.2 on 2026-02-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0014_daaluser_brand_daaluser_company_name_daaluser_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Master',
                'verbose_name_plural': 'Branch Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('seller_confirmed', 'Seller Confirmed'), ('buyer_confirmed', 'Buyer Confirmed'), ('deal_confirmed', 'Deal Confirmed'), ('rejected', 'Rejected')], db_index=True, default='interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='daaluser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='kyc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='kyc_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_status',
            field=models.CharField(choices=[('available', 'Available'), ('buyer_confirmed', 'Buyer Confirmed'), ('seller_confirmed', 'Seller Confirmed'), ('deal_confirmed', 'Deal Confirmed'), ('sold', 'Sold')], db_index=True, default='available', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_pending_confirmation', 'Sold Pending Confirmation'), ('sold', 'Sold')], db_index=True, default='available', max_length=40),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('user_management', 'User Management'), ('branch_management', 'Branch Management'), ('category_management', 'Category Management'), ('subcategory_management', 'Subcategory Management'), ('polish_management', 'Polish Management'), ('product_management', 'Product Management'), ('product_image_management', 'Product Image Management')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='branchmaster',
            index=models.Index(fields=['state'], name='brokers_app_state_8cfae4_idx'),
        ),
        migrations.AddIndex(
            model_name='branchmaster',
            index=models.Index(fields=['city'], name='brokers_app_city_21c444_idx'),
        ),
        migrations.AddIndex(
            model_name='branchmaster',
            index=models.Index(fields=['area'], name='brokers_app_area_606f70_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchmaster',
            constraint=models.UniqueConstraint(fields=('state', 'city', 'area'), name='unique_branch_state_city_area'),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='brokers_app.product'),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_product_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productinterest',
            index=models.Index(fields=['product', 'status'], name='brokers_app_product_43db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='productinterest',
            index=models.Index(fields=['seller', 'status'], name='brokers_app_seller__f1b19d_idx'),
        ),
        migrations.AddIndex(
            model_name='productinterest',
            index=models.Index(fields=['buyer', 'status'], name='brokers_app_buyer_i_4cf72b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinterest',
            constraint=models.UniqueConstraint(fields=('product', 'buyer'), name='unique_interest_per_buyer_product'),
        ),
    ]
