# Generated by Django 6.0.2 on 2026-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0015_branchmaster_productinterest_daaluser_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daaluser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
