# Generated by Django 6.0.2 on 2026-02-20 05:53

import brokers_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0017_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm']), brokers_app.models.validate_video_size]),
        ),
        migrations.AddField(
            model_name='subcategorymaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_status',
            field=models.CharField(choices=[('available', 'Available'), ('buyer_confirmed', 'Buyer Confirmed'), ('seller_confirmed', 'Seller Confirmed'), ('deal_confirmed', 'Deal Confirmed'), ('sold', 'Sold'), ('open', 'Open')], db_index=True, default='available', max_length=30),
        ),
    ]
