# Generated by Django 6.0.2 on 2026-02-20 11:48

import brokers_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0018_categorymaster_is_active_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daaluser',
            name='gst_image',
            field=models.ImageField(blank=True, null=True, upload_to='gst_images/', validators=[brokers_app.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_images/', validators=[brokers_app.models.validate_file_size]),
        ),
    ]
