# Generated by Django 6.0.2 on 2026-02-25 12:14

import brokers_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('brokers_app', '0019_alter_daaluser_gst_image_alter_daaluser_pan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('brand_name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Master',
                'verbose_name_plural': 'Brand Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('deal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_unit', models.CharField(max_length=10)),
                ('quantity_unit', models.CharField(max_length=10)),
                ('loading_from', models.CharField(max_length=200)),
                ('loading_to', models.CharField(max_length=200)),
                ('buyer_remark', models.TextField(blank=True, null=True)),
                ('seller_remark', models.TextField(blank=True, null=True)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='TagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag Master',
                'verbose_name_plural': 'Tag Master',
                'ordering': ['tag_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='polishing',
        ),
        migrations.RemoveField(
            model_name='subcategorymaster',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='categorymaster',
            options={'ordering': ['path', 'category_name'], 'verbose_name': 'Category Master', 'verbose_name_plural': 'Category Masters'},
        ),
        migrations.AlterModelOptions(
            name='productinterest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Interest', 'verbose_name_plural': 'Product Interests'},
        ),
        migrations.RemoveConstraint(
            model_name='productinterest',
            name='unique_interest_per_buyer_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='brokers_app.categorymaster'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='adharcard_image',
            field=models.FileField(blank=True, help_text='Upload Aadhaar card document', null=True, upload_to=brokers_app.models.user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), brokers_app.models.validate_document_file_size]),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='buyer_unique_id',
            field=models.CharField(blank=True, help_text='Unique identifier for buyers to show to sellers', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='shopact_image',
            field=models.FileField(blank=True, help_text='Upload Shop Act document', null=True, upload_to=brokers_app.models.user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), brokers_app.models.validate_document_file_size]),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='amount_unit',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON'), ('qtl', 'QUINTAL')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='loading_from',
            field=models.CharField(blank=True, help_text='Loading from location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='loading_to',
            field=models.CharField(blank=True, help_text='Loading to location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original quantity when product was created', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('ton', 'TON'), ('qtl', 'QUINTAL')], default='kg', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining quantity available for sale', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_products', to='brokers_app.categorymaster'),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='buyer_offered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='buyer_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='buyer_required_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='deal_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='loading_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='loading_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='negotiation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='seller_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='snapshot_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='snapshot_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='superadmin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='gst_image',
            field=models.FileField(blank=True, help_text='Upload GST certificate image', null=True, upload_to=brokers_app.models.user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), brokers_app.models.validate_document_file_size]),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='pan_image',
            field=models.FileField(blank=True, help_text='Upload PAN card image', null=True, upload_to=brokers_app.models.user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), brokers_app.models.validate_document_file_size]),
        ),
        migrations.AlterField(
            model_name='daaluser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('transporter', 'Transporter'), ('both_sellerandbuyer', 'Both Seller and Buyer')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_status',
            field=models.CharField(choices=[('available', 'Available'), ('partially_sold', 'Partially Sold'), ('seller_confirmed', 'Seller Confirmed'), ('deal_confirmed', 'Deal Confirmed'), ('out_of_stock', 'Out of Stock'), ('sold', 'Sold')], db_index=True, default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_pending_confirmation', 'Sold Pending Confirmation'), ('sold', 'Sold'), ('out_of_stock', 'Out of Stock')], db_index=True, default='available', max_length=40),
        ),
        migrations.AlterField(
            model_name='productinterest',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('seller_confirmed', 'Seller Confirmed'), ('deal_confirmed', 'Deal Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='interested', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('user_management', 'User Management'), ('branch_management', 'Branch Management'), ('category_management', 'Category Management'), ('subcategory_management', 'Subcategory Management'), ('brand_management', 'Brand Management'), ('product_management', 'Product Management'), ('product_image_management', 'Product Image Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('transporter', 'Transporter'), ('both_sellerandbuyer', 'Both Seller and Buyer')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='categorymaster',
            index=models.Index(fields=['parent'], name='brokers_app_parent__2daddb_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymaster',
            index=models.Index(fields=['level'], name='brokers_app_level_c37799_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymaster',
            index=models.Index(fields=['path'], name='brokers_app_path_eb4889_idx'),
        ),
        migrations.AddIndex(
            model_name='productinterest',
            index=models.Index(fields=['transaction_id'], name='brokers_app_transac_d725b7_idx'),
        ),
        migrations.AddField(
            model_name='brandmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brokers_app.brandmaster'),
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='interest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='brokers_app.productinterest'),
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='brokers_app.product'),
        ),
        migrations.AddField(
            model_name='contract',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daaluser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='brokers_app.tagmaster'),
        ),
        migrations.AddIndex(
            model_name='daaluser',
            index=models.Index(fields=['buyer_unique_id'], name='brokers_app_buyer_u_abce03_idx'),
        ),
        migrations.DeleteModel(
            name='PolishMaster',
        ),
        migrations.DeleteModel(
            name='subCategoryMaster',
        ),
        migrations.RemoveField(
            model_name='productinterest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='productinterest',
            name='offer_price',
        ),
    ]
