# Generated by Django 5.1.4 on 2026-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers_app', '0023_align_user_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='loading_from',
            field=models.DateField(blank=True, help_text='Loading start date', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='loading_to',
            field=models.DateField(blank=True, help_text='Loading end date', null=True),
        ),
    ]
